namespace FakeDataGenerator;

//Data obtained from Chat GPT
public class Data
{
    public static string[] AcademyNames { get; } =
    {
        "Academy Transformation Trust",
        "AET",
        "Ark Schools",
        "Aspirations Academies Trust",
        "Bohunt Education Trust",
        "Bourne Education Trust",
        "Castle Trust",
        "Chiltern Learning Trust",
        "Community Schools Trust",
        "Cooperative Academy Trust",
        "David Ross Education Trust",
        "Delta Academies Trust",
        "Dixons Academies Trust",
        "E-ACT",
        "Education South West",
        "EKC Group",
        "Evelyn Grace Academy Trust",
        "Excalibur Academies Trust",
        "Flying High Trust",
        "Fusion Academy Trust",
        "GALAXY Trust",
        "GLF Schools",
        "Greenwood Academies Trust",
        "Guildford Education Partnership",
        "Haberdashers' Adams Federation Trust",
        "Harris Federation",
        "Hartismere Family of Schools",
        "Headlands Academy Trust",
        "Heath Family (North West) Multi Academy Trust",
        "Inspiration Trust",
        "Isaac Newton Academy Trust",
        "Kesgrave High School Co-operative Trust",
        "King Edward VI Academy Trust",
        "King's Group Academies",
        "L.E.A.D. Academy Trust",
        "LDBS Academies Trust",
        "Learn Academies Trust",
        "Lilac Sky Schools Academy Trust",
        "Lion Academy Trust",
        "London Diocesan Board for Schools",
        "Lumen Learning Trust",
        "Maiden Erlegh Trust",
        "Matrix Academy Trust",
        "Mercian Trust",
        "Mid Essex Multi-Academy Trust",
        "Midlands Academy Trust",
        "Montsaye Community Learning Partnership",
        "Mossbourne Federation",
        "Ninestiles Academy Trust",
        "Oxford Diocesan Schools Trust",
        "Plymouth CAST",
        "Q3 Academies Trust",
        "Redhill Academy Trust",
        "St. Chad's Academies Trust",
        "TDET - Transforming Education in Dudley",
        "United Learning Trust",
        "Venturers Trust",
        "Wellspring Academy Trust"
    };
}