namespace FakeDataGenerator;

public class Data
{
    /// <summary>
    /// Trust names have been generated by Chat GPT AI and are fictional.
    /// Any resemblance to real Trusts is entirely unintentional. If you spot a
    /// real name then please raise a PR to correct it to a fake one
    /// </summary>
    public static string[] TrustNames { get; } =
    {
        "Abbey Lane Academies Trust",
        "Edify Multi-Academy Trust",
        "Innovate Academy Trust",
        "Momentum Multi-Academy Trust",
        "Vanguard Learning Trust",
        "Progressive Education Trust",
        "Horizon Multi-Academy Trust",
        "Elevate Schools Trust",
        "Visionary Academy Trust",
        "Empowerment Multi-Academy Trust",
        "Echelon Education Trust",
        "Ascendancy Academy Trust",
        "Nexus Multi-Academy Trust",
        "Merit Academy Trust",
        "Epic Learning Trust",
        "Peak Multi-Academy Trust",
        "Legacy Education Trust",
        "Acclivity Multi-Academy Trust",
        "Pinnacle Education Trust",
        "Thrive Multi-Academy Trust",
        "Elevated Schools Trust",
        "Champion Academy Trust",
        "Intrepid Education Trust",
        "Prospect Multi-Academy Trust",
        "New Horizons Trust",
        "Milestone Multi-Academy Trust",
        "Galvanize Academy Trust",
        "Cornerstone Multi-Academy Trust",
        "Inspire Multi-Academy Trust",
        "Success Multi-Academy Trust",
        "Bridge Education Trust",
        "Crescendo Academy Trust",
        "Potential Learning Trust",
        "Horizons Multi-Academy Trust",
        "Rise Education Trust",
        "Excel Multi-Academy Trust",
        "Unity Learning Trust",
        "Adept Academy Trust",
        "Excellence Multi-Academy Trust",
        "Prosperity Education Trust",
        "Pathfinder Multi-Academy Trust",
        "Vitality Academy Trust",
        "Forward Multi-Academy Trust",
        "Transcendence Education Trust",
        "Advantage Academy Trust",
        "Illuminate Multi-Academy Trust",
        "Fusion Education Trust",
        "Empower Academy Trust",
        "Illuminate Learning Trust",
        "Challenger Multi-Academy Trust"
    };

    public static string[] LocalAuthorities { get; } =
    {
        "Barnsley",
        "Bradford",
        "Calderdale",
        "Doncaster",
        "East Riding of Yorkshire",
        "Kingston upon Hull, City of",
        "Kirklees",
        "Leeds",
        "North East Lincolnshire",
        "North Lincolnshire",
        "North Yorkshire",
        "Rotherham",
        "Sheffield",
        "Wakefield",
        "York"
    };
}