namespace FakeDataGenerator;

//Data obtained from Chat GPT
public class Data
{
    public static string[] TrustNames { get; } =
    {
        "Academy Transformation Trust",
        "AET",
        "Ark Schools",
        "Aspirations Academies Trust",
        "Bohunt Education Trust",
        "Bourne Education Trust",
        "Castle Trust",
        "Chiltern Learning Trust",
        "Community Schools Trust",
        "Cooperative Academy Trust",
        "David Ross Education Trust",
        "Delta Academies Trust",
        "Dixons Academies Trust",
        "E-ACT",
        "Education South West",
        "EKC Group",
        "Evelyn Grace Academy Trust",
        "Excalibur Academies Trust",
        "Flying High Trust",
        "Fusion Academy Trust",
        "GALAXY Trust",
        "GLF Schools",
        "Greenwood Academies Trust",
        "Guildford Education Partnership",
        "Haberdashers' Adams Federation Trust",
        "Harris Federation",
        "Hartismere Family of Schools",
        "Headlands Academy Trust",
        "Heath Family (North West) Multi Academy Trust",
        "Inspiration Trust",
        "Isaac Newton Academy Trust",
        "Kesgrave High School Co-operative Trust",
        "King Edward VI Academy Trust",
        "King's Group Academies",
        "L.E.A.D. Academy Trust",
        "LDBS Academies Trust",
        "Learn Academies Trust",
        "Lilac Sky Schools Academy Trust",
        "Lion Academy Trust",
        "London Diocesan Board for Schools",
        "Lumen Learning Trust",
        "Maiden Erlegh Trust",
        "Matrix Academy Trust",
        "Mercian Trust",
        "Mid Essex Multi-Academy Trust",
        "Midlands Academy Trust",
        "Montsaye Community Learning Partnership",
        "Mossbourne Federation",
        "Ninestiles Academy Trust",
        "Oxford Diocesan Schools Trust",
        "Plymouth CAST",
        "Q3 Academies Trust",
        "Redhill Academy Trust",
        "St. Chad's Academies Trust",
        "TDET - Transforming Education in Dudley",
        "United Learning Trust",
        "Venturers Trust",
        "Wellspring Academy Trust"
    };

    public static string[] LocalAuthorities { get; } =
    {
        "Barking and Dagenham London Borough Council",
        "Barnet London Borough Council",
        "Barnsley Metropolitan Borough Council",
        "Bath and North East Somerset Council",
        "Bedford Borough Council",
        "Bexley London Borough Council",
        "Birmingham City Council",
        "Blackburn with Darwen Borough Council",
        "Blackpool Council",
        "Bolton Council",
        "Bournemouth Borough Council",
        "Bracknell Forest Council",
        "City of Bradford Metropolitan District Council",
        "Brent London Borough Council",
        "Brighton and Hove City Council",
        "Bristol City Council",
        "Bromley London Borough Council",
        "Buckinghamshire Council",
        "Bury Metropolitan Borough Council",
        "Calderdale Metropolitan Borough Council",
        "Cambridgeshire and Isle of Ely County Council",
        "Cambridgeshire County Council",
        "Camden London Borough Council",
        "Central Bedfordshire Council",
        "Cheshire East Council",
        "Cheshire West and Chester Council",
        "City of Doncaster Council",
        "City of London Corporation",
        "Cornwall Council",
        "Council of the Isles of Scilly",
        "Coventry City Council",
        "Croydon London Borough Council",
        "Cumberland Council",
        "Cumbria County Council",
        "Darlington Borough Council",
        "Derby City Council",
        "Derbyshire County Council",
        "Devon County Council",
        "Dorset Council (UK)",
        "Durham County Council",
        "Ealing London Borough Council",
        "East Riding of Yorkshire Council",
        "East Sussex County Council",
        "Enfield London Borough Council",
        "Essex County Council",
        "Gloucestershire County Council",
        "Greenwich London Borough Council",
        "Hackney London Borough Council",
        "Halton Borough Council",
        "Hammersmith and Fulham London Borough Council",
        "Hampshire County Council",
        "Haringey London Borough Council",
        "Harrow London Borough Council",
        "Hartlepool Borough Council",
        "Havering London Borough Council",
        "Herefordshire Council",
        "Hertfordshire County Council",
        "Hillingdon London Borough Council",
        "Holland County Council",
        "Hounslow London Borough Council",
        "Hull City Council",
        "Huntingdon and Peterborough County Council",
        "Huntingdonshire County Council",
        "Hyndburn Borough Council",
        "Isle of Ely County Council",
        "Isle of Wight Council",
        "Islington London Borough Council",
        "Kensington and Chelsea London Borough Council",
        "Kent County Council",
        "Kesteven County Council",
        "Kingston upon Thames London Borough Council",
        "Kirklees Council",
        "Knowsley Metropolitan Borough Council",
        "Lambeth London Borough Council",
        "Lancashire County Council",
        "Leeds City Council",
        "Leicester City Council",
        "Leicestershire County Council",
        "Lewisham London Borough Council",
        "Lincolnshire County Council",
        "Lindsey County Council",
        "Liverpool City Council",
        "Luton Borough Council",
        "Manchester City Council",
        "Medway Council",
        "Merton London Borough Council",
        "Middlesbrough Council",
        "Milton Keynes City Council",
        "Newcastle City Council",
        "Newham London Borough Council",
        "Norfolk County Council",
        "North East Lincolnshire Council",
        "North Lincolnshire Council",
        "North Somerset Council",
        "North Tyneside Council",
        "North Yorkshire Council",
        "North Yorkshire County Council",
        "Northumberland County Council",
        "Nottingham City Council",
        "Nottinghamshire County Council",
        "Oldham Council",
        "Oxfordshire County Council",
        "Peterborough City Council",
        "Plymouth City Council",
        "Poole Borough Council",
        "Portsmouth City Council",
        "Reading Borough Council",
        "Redbridge London Borough Council",
        "Redcar and Cleveland Borough Council",
        "Richmond upon Thames London Borough Council",
        "Rochdale Borough Council",
        "Rotherham Metropolitan Borough Council",
        "Rutland County Council",
        "Salford City Council",
        "Sandwell Metropolitan Borough Council",
        "Sefton Council",
        "Sheffield City Council",
        "Shropshire Council",
        "Slough Borough Council",
        "Soke of Peterborough County Council",
        "Solihull Metropolitan Borough Council",
        "Somerset County Council",
        "South Gloucestershire Council",
        "South Tyneside Council",
        "Southampton City Council",
        "Southend-on-Sea City Council",
        "Southwark London Borough Council",
        "St Helens Council",
        "Staffordshire County Council",
        "Stockport Metropolitan Borough Council",
        "Stockton-on-Tees Borough Council",
        "Stoke-on-Trent City Council",
        "Suffolk County Council",
        "Sunderland City Council",
        "Surrey County Council",
        "Sutton London Borough Council",
        "Swindon Borough Council",
        "Tameside Metropolitan Borough Council",
        "Telford and Wrekin Council",
        "Thurrock Council",
        "Torbay Council",
        "Tower Hamlets London Borough Council",
        "Trafford Council",
        "Wakefield Council",
        "Walsall Council",
        "Waltham Forest London Borough Council",
        "Wandsworth London Borough Council",
        "Warrington Borough Council",
        "Warwickshire County Council",
        "West Berkshire Council",
        "West Sussex County Council",
        "Westminster City Council",
        "Westmorland and Furness Council",
        "Wigan Metropolitan Borough Council",
        "Wiltshire Council",
        "Windsor and Maidenhead Borough Council",
        "Wirral Council",
        "Wokingham Borough Council",
        "Worcestershire County Council",
        "City of York Council"
    };
}